name: Lint & Format

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - name: Show how to fix lint
        if: ${{ failure() }}
        run: echo "Please run `npm run lint-fix` in your root directory to fix the lint automatically."
  format:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm run format-check
      - name: Show how to fix format
        if: ${{ failure() }}
        run: echo "Please run `npm run format` in your root directory to format automatically."
